allowing all plot functions within pulses.py to save the plot as a .png file
qiboteam/qibolab pull request #190
Opened 2022-10-15 08:26 UTC by aorgazf

This functionality is useful for debugging through the slurm queue

2022-10-15 15:21 UTC, DavidSarlle commented
Looks goot to me. It works.

2022-10-15 21:27 UTC, stavros11 approved these changes
Indeed, this is useful, thanks.

2022-10-16 07:50 UTC, scarrazza commented
Could you please try fix coverage so we can merge?

2022-10-16 09:50 UTC, scarrazza commented on src/qibolab/pulses.py
> +    def plot(self, savefig_filename=None):
Could you please document this function?

2022-10-16 09:51 UTC, scarrazza requested changes
Please include docstrings explaining what the method does and its arguments.

2022-10-16 09:51 UTC, scarrazza commented on src/qibolab/pulses.py
> +    def plot(self, savefig_filename=None):
Docstrings required also here.

2022-10-16 09:51 UTC, scarrazza commented on src/qibolab/pulses.py
> +    def plot(self, savefig_filename=None):
And here.

2022-10-19 10:22 UTC, merged