use reusable workflows
qiboteam/qibolab pull request #278
Opened 2023-01-24 05:37 UTC by Edoardo-Pedicillo

This PR modify the workflows in order to use the ones stored in `qiboteam/workflows` (see qiboteam/workflows#23).

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.

2023-02-01 12:27 UTC, AleCandido requested changes

2023-02-01 12:27 UTC, AleCandido commented on pyproject.toml
> +errors-only = true
```suggestion
```

2023-02-03 05:38 UTC, Edoardo-Pedicillo commented
@scarrazza This PR is ready to be merged.

2023-02-03 10:12 UTC, AleCandido approved these changes

2023-02-03 10:13 UTC, AleCandido requested changes

2023-02-03 10:13 UTC, AleCandido commented on pyproject.toml
> +exit-zero = true
Wait a second: you should not always exit with zero!

The first check on errors should actually crash if failing.

2023-02-03 10:13 UTC, AleCandido commented on pyproject.toml
> +errors-only = true
And you should also check for warnings, why did you revert?

2023-02-03 10:15 UTC, AleCandido approved these changes
My bad, I was only watching at one commit, but not the one after (current last)...

2023-02-03 20:52 UTC, scarrazza approved these changes

2023-02-03 20:53 UTC, merged