fix corrected qubit frequency after Ramswy fitting
qiboteam/qibolab pull request #426
Opened 2023-05-18 11:42 UTC by DavidSarlle

PR fixing issue detected in qibocal (https://github.com/qiboteam/qibocal/issues/337).
Now the delta_phys obtained in Ramsey routine is added or subtracted to the runcard qubit frequency  depending on the platform.

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.

2023-05-18 11:58 UTC, DavidSarlle commented
@andrea-pasquale this Pr also contains the latest qblox runcard from @aorgazf in order to test the changes

2023-05-18 12:39 UTC, andrea-pasquale requested changes
Thanks @DavidSarlle.
You can find below some comments.
I don't like the attribute `_update_called_by_multiqubit`.
I think that a possible solution will be to move the call to `update` from `AbstractPlatform`
https://github.com/qiboteam/qibolab/blob/0aff24d1daa606904cc578814e0d37f273de79ab/src/qibolab/platforms/multiqubit.py#L152
to the top of the method.
In this way in `MultiqubitPlatform` you should be able to correct everything without having to do weird things.
Let me know if you agree.

2023-05-18 12:39 UTC, andrea-pasquale commented on src/qibolab/platforms/abstract.py
> +        self._update_called_by_multiqubit = False
I don't like that fact that we need to add this method.
I think that we should be able to find a solution without adding this method.

2023-05-18 12:39 UTC, andrea-pasquale commented on src/qibolab/platforms/abstract.py
> +                        corrected_qubit_frequency = int(qubit_freq + delta_phys)
Same here.

2023-06-07 13:13 UTC, scarrazza commented
@DavidSarlle given this PR is getting obsolete, we have decided to close and create a new one using the latest main branch.

2023-06-07 13:13 UTC, closed without merging